import {
  Play,
  MessageSquare,
  Image,
  ListChecks,
  GitBranch,
  Clock,
  Database,
  Globe,
  Radio,
  Headphones,
  MessageCircleQuestion,
  Link
} from 'lucide-react';

// Define node types
export const nodeTypes = [
  {
    type: 'startTrigger',
    label: 'Start Trigger',
    description: 'Entry point for the flow',
    category: 'Triggers',
    icon: <Play size={18} />,
    color: 'bg-primary-100 text-primary-600 dark:bg-primary-900 dark:text-primary-300',
    iconBg: 'bg-primary-50 text-primary-500 dark:bg-primary-900/50 dark:text-primary-400',
  },
  {
    type: 'textMessage',
    label: 'Text Message',
    description: 'Send a text message',
    category: 'Messages',
    icon: <MessageSquare size={18} />,
    color: 'bg-blue-100 text-blue-600 dark:bg-blue-900 dark:text-blue-300',
    iconBg: 'bg-blue-50 text-blue-500 dark:bg-blue-900/50 dark:text-blue-400',
  },
  {
    type: 'mediaMessage',
    label: 'Media Message',
    description: 'Send image, video or document',
    category: 'Messages',
    icon: <Image size={18} />,
    color: 'bg-purple-100 text-purple-600 dark:bg-purple-900 dark:text-purple-300',
    iconBg: 'bg-purple-50 text-purple-500 dark:bg-purple-900/50 dark:text-purple-400',
  },
  {
    type: 'quickReplies',
    label: 'Quick Replies',
    description: 'Send buttons for quick response',
    category: 'Messages',
    icon: <Radio size={18} />,
    color: 'bg-green-100 text-green-600 dark:bg-green-900 dark:text-green-300',
    iconBg: 'bg-green-50 text-green-500 dark:bg-green-900/50 dark:text-green-400',
  },
  {
    type: 'actionButtons',
    label: 'Action Buttons',
    description: 'Send buttons with actions',
    category: 'Messages',
    icon: <Link size={18} />,
    color: 'bg-amber-100 text-amber-600 dark:bg-amber-900 dark:text-amber-300',
    iconBg: 'bg-amber-50 text-amber-500 dark:bg-amber-900/50 dark:text-amber-400',
  },
  {
    type: 'listMessage',
    label: 'List Message',
    description: 'Send interactive list',
    category: 'Messages',
    icon: <ListChecks size={18} />,
    color: 'bg-yellow-100 text-yellow-600 dark:bg-yellow-900 dark:text-yellow-300',
    iconBg: 'bg-yellow-50 text-yellow-500 dark:bg-yellow-900/50 dark:text-yellow-400',
  },
  {
    type: 'condition',
    label: 'Condition',
    description: 'If/Else logic branch',
    category: 'Logic',
    icon: <GitBranch size={18} />,
    color: 'bg-indigo-100 text-indigo-600 dark:bg-indigo-900 dark:text-indigo-300',
    iconBg: 'bg-indigo-50 text-indigo-500 dark:bg-indigo-900/50 dark:text-indigo-400',
  },
  {
    type: 'waitResponse',
    label: 'Wait for Response',
    description: 'Pause and await user input',
    category: 'Logic',
    icon: <MessageCircleQuestion size={18} />,
    color: 'bg-orange-100 text-orange-600 dark:bg-orange-900 dark:text-orange-300',
    iconBg: 'bg-orange-50 text-orange-500 dark:bg-orange-900/50 dark:text-orange-400',
  },
  {
    type: 'delay',
    label: 'Delay',
    description: 'Pause flow execution',
    category: 'Logic',
    icon: <Clock size={18} />,
    color: 'bg-gray-100 text-gray-600 dark:bg-gray-800 dark:text-gray-300',
    iconBg: 'bg-gray-50 text-gray-500 dark:bg-gray-700 dark:text-gray-400',
  },
  {
    type: 'setVariable',
    label: 'Set Variable',
    description: 'Store or update a variable',
    category: 'Logic',
    icon: <Database size={18} />,
    color: 'bg-teal-100 text-teal-600 dark:bg-teal-900 dark:text-teal-300',
    iconBg: 'bg-teal-50 text-teal-500 dark:bg-teal-900/50 dark:text-teal-400',
  },
  {
    type: 'httpRequest',
    label: 'HTTP Request',
    description: 'Call external API',
    category: 'Integration',
    icon: <Globe size={18} />,
    color: 'bg-red-100 text-red-600 dark:bg-red-900 dark:text-red-300',
    iconBg: 'bg-red-50 text-red-500 dark:bg-red-900/50 dark:text-red-400',
  },
  {
    type: 'humanTransfer',
    label: 'Human Transfer',
    description: 'Transfer to human agent',
    category: 'Integration',
    icon: <Headphones size={18} />,
    color: 'bg-pink-100 text-pink-600 dark:bg-pink-900 dark:text-pink-300',
    iconBg: 'bg-pink-50 text-pink-500 dark:bg-pink-900/50 dark:text-pink-400',
  },
];
