import {
  Play,
  MessageSquare,
  Image,
  ListChecks,
  GitBranch,
  Clock,
  Database,
  Globe,
  Radio,
  Headphones,
  MessageCircleQuestion,
  Link
} from 'lucide-react';

// Define node types
export const nodeTypes = [
  {
    type: 'startTrigger',
    label: 'Início',
    description: 'Ponto de entrada para o fluxo',
    category: 'Gatilhos',
    icon: <Play size={18} />,
    color: 'bg-primary-100 text-primary-600 dark:bg-primary-900 dark:text-primary-300',
    iconBg: 'bg-primary-50 text-primary-500 dark:bg-primary-900/50 dark:text-primary-400',
  },
  {
    type: 'textMessage',
    label: 'Mensagem de Texto',
    description: 'Enviar uma mensagem de texto',
    category: 'Mensagens',
    icon: <MessageSquare size={18} />,
    color: 'bg-blue-100 text-blue-600 dark:bg-blue-900 dark:text-blue-300',
    iconBg: 'bg-blue-50 text-blue-500 dark:bg-blue-900/50 dark:text-blue-400',
  },
  {
    type: 'mediaMessage',
    label: 'Mensagem com Mídia',
    description: 'Enviar imagem, vídeo ou documento',
    category: 'Mensagens',
    icon: <Image size={18} />,
    color: 'bg-purple-100 text-purple-600 dark:bg-purple-900 dark:text-purple-300',
    iconBg: 'bg-purple-50 text-purple-500 dark:bg-purple-900/50 dark:text-purple-400',
  },
  {
    type: 'quickReplies',
    label: 'Respostas Rápidas',
    description: 'Enviar botões para resposta rápida',
    category: 'Mensagens',
    icon: <Radio size={18} />,
    color: 'bg-green-100 text-green-600 dark:bg-green-900 dark:text-green-300',
    iconBg: 'bg-green-50 text-green-500 dark:bg-green-900/50 dark:text-green-400',
  },
  {
    type: 'actionButtons',
    label: 'Botões de Ação',
    description: 'Enviar botões com ações',
    category: 'Mensagens',
    icon: <Link size={18} />,
    color: 'bg-amber-100 text-amber-600 dark:bg-amber-900 dark:text-amber-300',
    iconBg: 'bg-amber-50 text-amber-500 dark:bg-amber-900/50 dark:text-amber-400',
  },
  {
    type: 'listMessage',
    label: 'Mensagem em Lista',
    description: 'Enviar lista interativa',
    category: 'Mensagens',
    icon: <ListChecks size={18} />,
    color: 'bg-yellow-100 text-yellow-600 dark:bg-yellow-900 dark:text-yellow-300',
    iconBg: 'bg-yellow-50 text-yellow-500 dark:bg-yellow-900/50 dark:text-yellow-400',
  },
  {
    type: 'condition',
    label: 'Condição',
    description: 'Ramificação lógica Se/Senão',
    category: 'Lógica',
    icon: <GitBranch size={18} />,
    color: 'bg-indigo-100 text-indigo-600 dark:bg-indigo-900 dark:text-indigo-300',
    iconBg: 'bg-indigo-50 text-indigo-500 dark:bg-indigo-900/50 dark:text-indigo-400',
  },
  {
    type: 'waitResponse',
    label: 'Aguardar Resposta',
    description: 'Pausar e aguardar entrada do usuário',
    category: 'Lógica',
    icon: <MessageCircleQuestion size={18} />,
    color: 'bg-orange-100 text-orange-600 dark:bg-orange-900 dark:text-orange-300',
    iconBg: 'bg-orange-50 text-orange-500 dark:bg-orange-900/50 dark:text-orange-400',
  },
  {
    type: 'delay',
    label: 'Atraso',
    description: 'Pausar execução do fluxo',
    category: 'Lógica',
    icon: <Clock size={18} />,
    color: 'bg-gray-100 text-gray-600 dark:bg-gray-800 dark:text-gray-300',
    iconBg: 'bg-gray-50 text-gray-500 dark:bg-gray-700 dark:text-gray-400',
  },
  {
    type: 'setVariable',
    label: 'Definir Variável',
    description: 'Armazenar ou atualizar uma variável',
    category: 'Lógica',
    icon: <Database size={18} />,
    color: 'bg-teal-100 text-teal-600 dark:bg-teal-900 dark:text-teal-300',
    iconBg: 'bg-teal-50 text-teal-500 dark:bg-teal-900/50 dark:text-teal-400',
  },
  {
    type: 'httpRequest',
    label: 'Requisição HTTP',
    description: 'Chamar API externa',
    category: 'Integração',
    icon: <Globe size={18} />,
    color: 'bg-red-100 text-red-600 dark:bg-red-900 dark:text-red-300',
    iconBg: 'bg-red-50 text-red-500 dark:bg-red-900/50 dark:text-red-400',
  },
  {
    type: 'humanTransfer',
    label: 'Transferir para Humano',
    description: 'Transferir para atendente humano',
    category: 'Integração',
    icon: <Headphones size={18} />,
    color: 'bg-pink-100 text-pink-600 dark:bg-pink-900 dark:text-pink-300',
    iconBg: 'bg-pink-50 text-pink-500 dark:bg-pink-900/50 dark:text-pink-400',
  },
];
